### ISSUE TITLE
Unselect problem in IE11 (Bug)

### ISSUE THREAD

**Issue by Jubayer-** [ivirabyan/jquery-mentions#34] opened 2015-05-04 06:24 UTC
Here is the steps to produce the bug:
-- Just add a mention in textarea in IE11 and then type nothing
-- Then remove the focus to somewhere else and focus in textarea again at the end of the text
-- Now press space. You'll see the previous selected mention is unselected

**Comment by ivirabyan** [comment] 2015-05-05 12:41
I just fixed related issue, please get the latest code and try it again. Tell me if the problem still exists.

**Comment by Jubayer-** [comment] 2015-05-06 08:11
I think we have another problem now. Updated file is not working when you select from list. I don't see any background after selection. Will you check it?

**Comment by ivirabyan** [comment] 2015-05-06 17:25
Yes, I broke the code in the last commit. Now it must work properly

**Comment by Jubayer-** [comment] 2015-05-07 06:04
This issue is solved but another same type issue came up. (-_-'')
For example after selecting alex and then typing something before alex will make it unselected. This didn't happen before.

Appreciates your works. Let me know after solving this one and thanks for updating fast.

**Comment by ivirabyan** [comment] 2015-05-07 08:25
Such problems may come up, since I completely changed mechanics of tracking mentions. So I need to debug it a little. I can't reproduce it in chrome though, I'll try IE11 bit later.

**Comment by Jubayer-** [comment] 2015-05-07 09:02
Thanks for the reply. Yes it does need debugging. I think i found a way to produce one problem in chrome:
-- From your demo example. At 1st delete all texts from text area
-- Now select alex
-- now press the key left arrow once and then the right arrow once. You'll see the caret is gone. and if you type something then alex will be unselected.

I'll let you know if i find any way to produce other problems

Thanks

**Comment by Jubayer-** [comment] 2015-05-07 13:43
Alright it starts auto deselecting mentions after selecting from the list. Here is how:
-- 1st select alex from list and set the caret posing before alex and press enter
-- now typing anything will deselect alex. :) 

Hope that'll help.

**Comment by ivirabyan** [comment] 2015-05-13 21:27
For some reason I can't reproduce it in chrome. Still  haven't tested it in IE

**Comment by ivirabyan** [comment] 2015-06-23 13:51
Duplicate of issue #35

**Closed by ivirabyan** 2015-06-23 13:51 UTC
Labels: bug, duplicate
